services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Lukasbableck\ContaoSVGIconPickerBundle\:
        resource: ../src
    Lukasbableck\ContaoSVGIconPickerBundle\Provider\SVGIconProvider:
        public: true
